app/count/routes.py
import datetime
import json
import logging
from flask import Blueprint, request
from jsonschema import validate, ValidationError
from app.database.models import CountEntry
from app.database.database import db
from ..data import DataReceiver
import app.util as util

count_bp = Blueprint('count', __name__)

_dataReceiver = DataReceiver.get_instance()

with open('app/count/schemas.json', 'r') as schemas_file:
    _schemas = json.load(schemas_file)

@count_bp.route('update', methods= ['GET'])
def get_count():
    return "ok", 200

@count_bp.route('/update', methods = ['POST'])
def update_count():
    data = request.get_json()
    #logging.debug("count post request from %d (ip: %s)", data['id'], request.remote_addr)

    try:
        validate(data, _schemas.get('countentry'))
        data['timestamp'] = datetime.datetime.strptime(data.get('timestamp', ''), '%Y-%m-%d %H:%M:%S')
        data['latitude'] = util.float_or_None(data.get('latitude', None))
        data['longitude'] = util.float_or_None(data.get('longitude', None))

    except ValidationError as e:
        logging.error("Validation error validating update")
        logging.error(e)
        return "Validation error", 400
    except ValueError:
        logging.error("Validation error when parsing date")
        return "Validation error - check date format %Y-%m-%d %H:%M:%S", 400

    entry = CountEntry.of_dict(data)
    existingEntry = db.session.query(CountEntry).filter_by(id=entry.id, timestamp=entry.timestamp).first()
    if not existingEntry:
        db.session.add(entry)
        db.session.commit()
        _dataReceiver.set_data(data)
    return "ok", 200

app/monitor/routes.py
from flask import Blueprint, request, jsonify, render_template, session
from app.database.models import TransitDetection, TransitEntry, TravelTime
from datetime import datetime
from contextlib import contextmanager
from app.database.database import db
from app.data import DataReceiver
import pytz
import json

TRANSIT_CONFIG_PATH = 'res/last_transit_config.json'

@contextmanager
def session_scope():
    session = db.session()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()

monitor_bp = Blueprint('monitor', __name__)
_data = DataReceiver.get_instance()

@monitor_bp.route('/update_checkbox', methods=['POST'])
def update_checkbox():
    data = request.get_json()
    online_only = data.get('online_only', False)
    session['online_only'] = online_only
    return jsonify({"message": "Checkbox state updated", "online_only": online_only})

@monitor_bp.route('/count_latest')
def get_count_latest():
    return render_template('monitor/count_page.html')

@monitor_bp.route('/count_table', methods=['GET'])
def get_count_data():
    local_timezone = pytz.timezone('Asia/Tokyo')
    online_only = session.get('online_only', False)
    data = {'online_only': online_only, 'update_time': datetime.now(local_timezone).strftime("%Y-%m-%d %H:%M:%S"), 'data': _data.get_data_online_first()}
    return render_template('monitor/count_table.html', data=data)

@monitor_bp.route('/transit_latest')
def get_transit_latest():
    return render_template('monitor/transit_data_page.html')

@monitor_bp.route('/transit_data_table', methods=['GET'])
def get_transit_data():
    with session_scope() as session:
        data_newest = session.query(TransitDetection).order_by(
            TransitDetection.timestamp.desc()
        ).limit(30).all()
        data_oldest = session.query(TransitDetection).order_by(
            TransitDetection.timestamp.asc()
        ).limit(30).all()
        data_oldest.reverse()

        data_rows = [{'id': result.device_id, 'timestamp': result.timestamp, 'close_list': result.close_code} for result in data_newest]
        data_rows.append({'id': '...', 'timestamp': '...', 'close_list': '...'})
        data_rows.extend([{'id': result.device_id, 'timestamp': result.timestamp, 'close_list': result.close_code} for result in data_oldest])

    local_timezone = pytz.timezone('Asia/Tokyo')
    data = {'update_time': datetime.now(local_timezone).strftime("%Y-%m-%d %H:%M:%S"), 'data': data_rows}
    return render_template('monitor/transit_data_table.html', data=data)

@monitor_bp.route('/transit_events')
def get_transit_results():
    return render_template('monitor/transit_event_page.html')

@monitor_bp.route('/transit_event_table', methods=['GET'])
def get_transit_times():
    latest_data = TransitEntry.query.order_by(
        TransitEntry.timestamp.desc()
    ).limit(50).all()

    result = []
    for data in latest_data:
        result.append({
            'from': data.scanner_from,
            'to': data.scanner_to,
            'code': data.code,
            'start': data.time_start,
            'end': data.time_end,
            'travel_time': data.travel_time,
            'timestamp': data.timestamp
        })

    result = sorted(result, key=lambda x: x['timestamp'], reverse=True)

    local_timezone = pytz.timezone('Asia/Tokyo')
    data = {'update_time': datetime.now(local_timezone).strftime("%Y-%m-%d %H:%M:%S"), 'data': result}
        
    return render_template('monitor/transit_event_table.html', data=data)

@monitor_bp.route('/travel_time')
def get_travel_results():
    return render_template('monitor/travel_time_page.html')

@monitor_bp.route('/travel_time_table', methods=['GET'])
def get_travel_data():
    with open(TRANSIT_CONFIG_PATH, 'r') as file:
        config = json.load(file)
    combinations = config.get('combinations', [])

    result = []

    with session_scope() as session:
        for combination in combinations:
            entry = session.query(TravelTime).filter_by(
                scanner_from=combination[0],
                scanner_to=combination[1]
            ).order_by(
                TravelTime.timestamp.desc()
            ).first()


            if entry:
                result.append({
                    'from': entry.scanner_from,
                    'to': entry.scanner_to,
                    'travel_time': entry.travel_time,
                    'average_speed': combination[2] / entry.travel_time,
                    'timestamp': entry.timestamp
                })

    local_timezone = pytz.timezone('Asia/Tokyo')
    data = {'update_time': datetime.now(local_timezone).strftime("%Y-%m-%d %H:%M:%S"), 'data': result}
        
    return render_template('monitor/travel_time_table.html', data=data)

@monitor_bp.route('/graph_count')
def get_graph_count():
    return render_template('monitor/graph_count.html')

@monitor_bp.route('/graph_travel_time')
def get_graph_travel_time():
    return render_template('monitor/graph_travel_time.html')

app/templates/monitor/count_graph.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>BleScan Graph</title>
    <style>
        .container {
            display: flex;
            justify-content: space-between;
        }

        .input-container {
            flex-grow: 0;
            margin-left: 40px;
            margin-right: 60px;
        }

        .input-box {
            width: 75px;
            text-align: center;
        }
    </style>
</head>

<body>
    <!-- <h1>Blescan Data</h1>
    <button onclick="window.location.href='/';">
        Back to frontpage
    </button>
    <label>     Last updated:</label>
    <label id="update_timestamp">XX</label> -->

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.1/nouislider.min.js"
        integrity="sha512-UOJe4paV6hYWBnS0c9GnIRH8PLm2nFK22uhfAvsTIqd3uwnWsVri1OPn5fJYdLtGY3wB11LGHJ4yPU1WFJeBYQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.1/nouislider.css"
        integrity="sha512-MKxcSu/LDtbIYHBNAWUQwfB3iVoG9xeMCm32QV5hZ/9lFaQZJVaXfz9aFa0IZExWzCpm7OWvp9zq9gVip/nLMg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <div>
        <div class="container">
            <div class="input-container">
                <label for="device-from" >Restrict devices from </label>
                <input type="number" id="device-from" name="id-from" step="1" min="1" max="100" value="1" class="input-box"/>
                <label for="device-to" > to </label>
                <input type="number" id="device-to" name="id-to" step="1" min="1" max="100" value="100" class="input-box"/>
            </div>
            <div class="input-container">
                <label for="input-limit" >Time limit (in hours)</label>
                <input type="number" id="input-limit" name="limit" step="0.5" min="0.5" max="48" value="2" class="input-box"/>
            </div>
            <div class="input-container">
                <label style="width: 100px;"></label>
            </div>
            <div class="input-container">
                <button id="btnUpdate" onclick="updateData()">
                    Update settings
                </button>
            </div>
        </div>
    </div>

    <div style="padding: 1cm; padding-bottom: 0%; ">
        <canvas id="myChart" style="width: 95vw !important; height: 92vh !important; "></canvas>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@^1"></script>

    <script>

        var chart = new Chart("myChart", {
            type: "line",
            data: {
                datasets: [{
                    label: "BLE detected (smoothed)",
                    data: [],
                    spanGaps: 10000
                },
                {
                    label: "Scanners online",
                    data: [],
                    spanGaps: 10000
                }

                ]
            },
            options: {
                responsive: true,
                maintainAspectRation: false,
                legend: { display: true },
                scales: {
                    x: {
                        type: 'time'
                    }
                }
            }
        });

        var firstDate = null;
        var firstDateSec = null;
        var lastDate = null;
        var lastDateSec = null;

        FORMAT = "%Y-%m-%d %H:%M:%S";
        FORMAT_JS = "YYYY-MM-DD HH:mm:ss";
        DATA_LIMIT = 8460 * 1.5;
        ID_FROM = 1;
        ID_TO = 100;

        function setValues(data) {

            var rolling_avg = [];
            var device_count = [];

            data.forEach(e => {
                rolling_avg.push({x: e.timestamp, y: e.rolling_avg_sum});
                device_count.push({x: e.timestamp, y: e.device_count});
            });

            chart.data.datasets[0].data = rolling_avg;
            chart.data.datasets[1].data = device_count;
            chart.update();

        }

        async function fetchData() {
            var url = "/database/data?limit=" + (DATA_LIMIT);
            url += "&id-from=" + (ID_FROM);
            url += "&id-to=" + (ID_TO);
            url += "&format=" + (FORMAT);
            console.log("fetching data (" + url + ")" );
            await fetch(url, {
                method: 'GET'
            })
                .then(response => response.json())
                .then(data => {
                    setValues(data);
                }).catch(error => {
                    console.error('Error:', error);
                })
        }

        function updateData() {
            time = new Date().toLocaleTimeString();
            let data_limit = parseFloat(document.getElementById("input-limit").value);
            if (data_limit > 0 ) {
                DATA_LIMIT = data_limit;
            }
            let id_from = parseInt(document.getElementById("device-from").value);
            if (id_from > 0 ) {
                ID_FROM = id_from;
            }
            let id_to = parseInt(document.getElementById("device-to").value);
            if (id_to > 0 ) {
                ID_TO = id_to;
            }
            DATA_LIMIT = Math.round(DATA_LIMIT * 360)
            fetchData();
            document.getElementById("update_timestamp").innerHTML = time;
        }
    
        setInterval(updateData, 10000);

    </script>
</body>

</html>

app/templates/monitor/count_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>BleScan Count Data</title>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#online_only').change(function() {
                var isChecked = $(this).is(':checked');
                $.ajax({
                    type: 'POST',
                    url: "{{ url_for('monitor.update_checkbox') }}",
                    data: JSON.stringify({ online_only: isChecked }),
                    contentType: 'application/json',
                    success: function(response) {
                        console.log(response);
                    }
                });
            });
        });
    </script>
</head>

<body>
    <h1>Blescan Count Data</h1> 
    <button onclick="window.location.href='/';">
        Back to frontpage
    </button>
    <br><br>

    <script src="https://unpkg.com/htmx.org@1.9.8"></script>

    <form action="{{ url_for('monitor.update_checkbox') }}" method="POST">
        <label for="online_only">Show only online devices</label>
        <input type="checkbox" id="online_only" name="online_only">
    </form>

    <br>

    <div id="item_table"></div>
            
    <script>
        const hiddenRows = new Set();

        document.addEventListener('DOMContentLoaded', function() {
            setInterval(updateTable, 5000);
        });

        function updateTable() {
            htmx.ajax('GET', 'count_table', { target: '#item_table', swap: 'innerHTML' });
        }
    </script>
    
</body>
</html>

app/templates/monitor/count_table.html
<div>
    Last updated: {{data.update_time}} <br>
    <table style="width: 80%;" border="2" cellpadding="4">

        <TR>
            <td>ID</td>
            <td>Total count</td>
            <td>Instant count</td>
            <td>Static count</td>
            <td>Instant/Total</td>
            <td>Static/Total</td>
            <td>Instant/Static</td>
            <td>Scan time</td>
            <td>Mean RSSI</td>
            <td>Settings</td>
            <td>Last update</td>
            <td>Update delta</td>
            <td>Online?</td>
        </TR>

        {% for item in data.data %}
            {% if item.tot_all >= 0 %}
                {% if (data.online_only and item.last_updated|is_online()) or (data.online_only == False) %}
                    <TR>
                        <td class="c1">{{item.id}}</td>
                        <td>{{item.tot_all}} ({{item.tot_close}})</td>
                        <td>{{ '%.1f'|format(item.inst_all) }} ({{ '%.1f'|format(item.inst_close) }})</td>
                        <td>{{item.stat_all}} ({{item.stat_close}})</td>
                        {% if item.tot_all > 0 and item.tot_close > 0%}
                            <td>{{ '%.2f'|format(item.inst_all / item.tot_all) }} ({{ '%.2f'|format(item.inst_close / item.tot_close) }})</td>
                            <td>{{ '%.2f'|format(item.stat_all / item.tot_all) }} ({{ '%.2f'|format(item.stat_close / item.tot_close) }})</td>
                        {% else %}
                            <td>N/A</td>
                            <td>N/A</td>
                        {% endif %}
                        {% if item.stat_all > 0 and item.stat_close > 0%}
                            <td>{{ '%.2f'|format(item.inst_all / item.stat_all) }} ({{ '%.2f'|format(item.inst_close / item.stat_close) }})</td>
                        {% else %}
                            <td>N/A</td>
                        {% endif %}
                        <td>{{ '%.2f'|format(item.scantime / item.scans) }} ({{item.scans}})</td>
                        {% if item.rssi_avg < 0%}
                            <td>{{ '%.2f'|format(item.rssi_avg) }}</td>
                        {% else %}
                            <td>N/A</td>
                        {% endif %}
                        <td>{{item.rssi_thresh}}, {{item.static_ratio}}</td>
                        <td>{{ item.timestamp.strftime('%a %d.%m.%Y %H:%M:%S') }}</td>
                        <td>{{item.last_updated|format_datetime('delta')}}</td>
                        <td>{{item.last_updated|is_online()}}</td>
                    </TR>
                {% endif %}
            {% else %}
                <TR>
                    <TD class="c1">{{item.id}}</td>
                    <td>N/A</td>
                    <td>N/A</td>
                    <td>N/A</td>
                    <td>N/A</td>
                    <td>N/A</td>
                    <td>N/A</td>
                    <td>N/A</td>
                    <td>N/A</td>
                    <td>N/A</td>
                    <td>N/A</td>
                    <td>N/A</td>
                    <td>Never</td>
                </TR>
            {% endif %}
        {% endfor %}

    </table>
</div>

app/templates/monitor/graph_count.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>BleScan Count Graph</title>
    <style>
        .container {
            display: flex;
            justify-content: space-between;
        }

        .input-container {
            flex-grow: 0;
            margin-left: 40px;
            margin-right: 60px;
        }

        .input-box {
            width: 75px;
            text-align: center;
        }
    </style>
</head>

<body>
    <!-- <h1>Blescan Data</h1>
    <button onclick="window.location.href='/';">
        Back to frontpage
    </button>
    <label>     Last updated:</label>
    <label id="update_timestamp">XX</label> -->

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.1/nouislider.min.js"
        integrity="sha512-UOJe4paV6hYWBnS0c9GnIRH8PLm2nFK22uhfAvsTIqd3uwnWsVri1OPn5fJYdLtGY3wB11LGHJ4yPU1WFJeBYQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.1/nouislider.css"
        integrity="sha512-MKxcSu/LDtbIYHBNAWUQwfB3iVoG9xeMCm32QV5hZ/9lFaQZJVaXfz9aFa0IZExWzCpm7OWvp9zq9gVip/nLMg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <div>
        <div class="container">
            <div class="input-container">
                <label for="device-from" >Restrict devices from </label>
                <input type="number" id="device-from" name="id-from" step="1" min="1" max="100" value="1" class="input-box"/>
                <label for="device-to" > to </label>
                <input type="number" id="device-to" name="id-to" step="1" min="1" max="100" value="100" class="input-box"/>
            </div>
            <div class="input-container">
                <label for="input-limit" >Time limit (in points)</label>
                <input type="number" id="input-limit" name="limit" step="5.0" min="10" max="5760" value="1440" class="input-box"/>
            </div>
            <div class="input-container">
                <label style="width: 100px;"></label>
            </div>
            <div class="input-container">
                <button id="btnUpdate" onclick="updateData()">
                    Update settings
                </button>
            </div>
        </div>
    </div>

    <div style="padding: 1cm; padding-bottom: 0%; ">
        <canvas id="myChart" style="width: 95vw !important; height: 92vh !important; "></canvas>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@^1"></script>

    <script>

        var chart = new Chart("myChart", {
            type: "line",
            data: {
                datasets: [{
                    label: "BLE detected (smoothed)",
                    data: [],
                    spanGaps: 10000
                },
                {
                    label: "Scanners online",
                    data: [],
                    spanGaps: 10000
                }

                ]
            },
            options: {
                responsive: true,
                maintainAspectRation: false,
                legend: { display: true },
                scales: {
                    x: {
                        type: 'time'
                    }
                }
            }
        });

        var firstDate = null;
        var firstDateSec = null;
        var lastDate = null;
        var lastDateSec = null;

        FORMAT = "%Y-%m-%d %H:%M:%S";
        FORMAT_JS = "YYYY-MM-DD HH:mm:ss";
        DATA_LIMIT = (48 * 3600) / 30;
        ID_FROM = 1;
        ID_TO = 100;

        function setValues(data) {

            var rolling_avg = [];
            var device_count = [];

            data.forEach(e => {
                rolling_avg.push({x: e.timestamp, y: e.rolling_avg_count});
                device_count.push({x: e.timestamp, y: e.device_count});
            });

            chart.data.datasets[0].data = rolling_avg;
            chart.data.datasets[1].data = device_count;
            chart.update();

        }

        async function fetchData() {
            var url = "/database/data_count?limit=" + (DATA_LIMIT);
            url += "&id-from=" + (ID_FROM);
            url += "&id-to=" + (ID_TO);
            url += "&format=" + (FORMAT);
            console.log("fetching data (" + url + ")" );
            await fetch(url, {
                method: 'GET'
            })
                .then(response => response.json())
                .then(data => {
                    setValues(data);
                }).catch(error => {
                    console.error('Error:', error);
                })
        }

        function updateData() {
            time = new Date().toLocaleTimeString();
            let data_limit = parseFloat(document.getElementById("input-limit").value);
            if (data_limit > 0 ) {
                DATA_LIMIT = data_limit;
            }
            let id_from = parseInt(document.getElementById("device-from").value);
            if (id_from > 0 ) {
                ID_FROM = id_from;
            }
            let id_to = parseInt(document.getElementById("device-to").value);
            if (id_to > 0 ) {
                ID_TO = id_to;
            }
            DATA_LIMIT = Math.round(DATA_LIMIT)
            fetchData();
        }
    
        setInterval(updateData, 10000);

    </script>
</body>

</html>

app/templates/monitor/graph_travel_time.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>BleScan Travel Time Graph</title>
    <style>
        .container {
            display: flex;
            justify-content: space-between;
        }

        .input-container {
            flex-grow: 0;
            margin-left: 40px;
            margin-right: 60px;
        }

        .input-box {
            width: 75px;
            text-align: center;
        }
    </style>
</head>

<body>
    <!-- <h1>Blescan Data</h1>
    <button onclick="window.location.href='/';">
        Back to frontpage
    </button>
    <label>     Last updated:</label>
    <label id="update_timestamp">XX</label> -->

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.1/nouislider.min.js"
        integrity="sha512-UOJe4paV6hYWBnS0c9GnIRH8PLm2nFK22uhfAvsTIqd3uwnWsVri1OPn5fJYdLtGY3wB11LGHJ4yPU1WFJeBYQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.1/nouislider.css"
        integrity="sha512-MKxcSu/LDtbIYHBNAWUQwfB3iVoG9xeMCm32QV5hZ/9lFaQZJVaXfz9aFa0IZExWzCpm7OWvp9zq9gVip/nLMg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <div>
        <div class="container">
            <div class="input-container">
                <label for="route-from" >Route from </label>
                <input type="number" id="route-from" name="id-from" step="1" min="1" max="100" value="1" class="input-box"/>
                <label for="route-to" > to </label>
                <input type="number" id="route-to" name="id-to" step="1" min="1" max="100" value="100" class="input-box"/>
            </div>
            <div class="input-container">
                <label for="input-limit" >Time limit (in points)</label>
                <input type="number" id="input-limit" name="limit" step="5.0" min="10" max="5760" value="1440" class="input-box"/>
            </div>
            <div class="input-container">
                <label style="width: 100px;"></label>
            </div>
            <div class="input-container">
                <button id="btnUpdate" onclick="updateData()">
                    Update settings
                </button>
            </div>
        </div>
    </div>

    <div style="padding: 1cm; padding-bottom: 0%; ">
        <canvas id="myChart" style="width: 95vw !important; height: 92vh !important; "></canvas>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@^1"></script>

    <script>

        var chart = new Chart("myChart", {
            type: "line",
            data: {
                datasets: [{
                    label: "Travel time (smoothened) [s]",
                    data: [],
                    spanGaps: 10000
                }]
            },
            options: {
                responsive: true,
                maintainAspectRation: false,
                legend: { display: true },
                scales: {
                    x: {
                        type: 'time'
                    }
                }
            }
        });

        var firstDate = null;
        var firstDateSec = null;
        var lastDate = null;
        var lastDateSec = null;

        FORMAT = "%Y-%m-%d %H:%M:%S";
        FORMAT_JS = "YYYY-MM-DD HH:mm:ss";
        DATA_LIMIT = (48 * 3600) / 30;
        ID_FROM = 1;
        ID_TO = 100;

        function setValues(data) {

            var rolling_avg = [];

            data.forEach(e => {
                rolling_avg.push({x: e.timestamp, y: e.rolling_avg_travel_time});
            });

            chart.data.datasets[0].data = rolling_avg;
            chart.update();

        }

        async function fetchData() {
            var url = "/database/data_travel_time?limit=" + (DATA_LIMIT);
            url += "&id-from=" + (ID_FROM);
            url += "&id-to=" + (ID_TO);
            url += "&format=" + (FORMAT);
            console.log("fetching data (" + url + ")" );
            await fetch(url, {
                method: 'GET'
            })
                .then(response => response.json())
                .then(data => {
                    setValues(data);
                }).catch(error => {
                    console.error('Error:', error);
                })
        }

        function updateData() {
            time = new Date().toLocaleTimeString();
            let data_limit = parseFloat(document.getElementById("input-limit").value);
            if (data_limit > 0 ) {
                DATA_LIMIT = data_limit;
            }
            let id_from = parseInt(document.getElementById("route-from").value);
            if (id_from > 0 ) {
                ID_FROM = id_from;
            }
            let id_to = parseInt(document.getElementById("route-to").value);
            if (id_to > 0 ) {
                ID_TO = id_to;
            }
            DATA_LIMIT = Math.round(DATA_LIMIT)
            fetchData();
        }
    
        setInterval(updateData, 10000);

    </script>
</body>

</html>

app/templates/monitor/transit_data_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>BleScan Transit Data</title>
</head>

<body>
    <h1>Blescan Transit Data</h1> 
    <button onclick="window.location.href='/';">
        Back to frontpage
    </button>
    <br><br>

    <script src="https://unpkg.com/htmx.org@1.9.8"></script>

    <label>
        <input type="checkbox" id="pauseUpdates"> Pause updates
    </label>

    <br><br>

    <div id="item_table"></div>
            
    <script>
        const hiddenRows = new Set();

        document.addEventListener('DOMContentLoaded', function() {
            setInterval(updateTable, 5000);
        });

        function updateTable() {
            const isPaused = document.getElementById('pauseUpdates').checked;
            if (isPaused) return;
            htmx.ajax('GET', 'transit_data_table', { target: '#item_table', swap: 'innerHTML' });
        }
    </script>
    
</body>
</html>